# Generated by Django 3.1.4 on 2020-12-29 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('keyword', models.CharField(max_length=256, verbose_name='Keyword')),
                ('description', models.TextField(verbose_name='Description')),
                ('Agreements', models.TextField(verbose_name='利用規約')),
                ('PrivacyPolicy', models.TextField(verbose_name='プライバシーポリシー')),
                ('AboutMe', models.TextField(verbose_name='サイト説明')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
