# Generated by Django 3.1.4 on 2021-01-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='タイトル')),
                ('title_ja', models.CharField(max_length=128, verbose_name='日本語タイトル')),
                ('year', models.CharField(max_length=16, verbose_name='公開年')),
                ('imdb_id', models.CharField(max_length=32, verbose_name='IMDb ID')),
                ('img_path', models.ImageField(upload_to='poster', verbose_name='ポスター画像Path')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
